[[libxls]]
arch = "aarch64"
git-tree-sha1 = "1892c7c02c852c696ead3a2e8c400294165bfb9d"
os = "macos"

    [[libxls.download]]
    sha256 = "c682052ff7555b23fb47faf9b7ee74ddf0595cc6a1ed886a79f02ac34c559e5a"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.aarch64-apple-darwin.tar.gz"
[[libxls]]
arch = "aarch64"
git-tree-sha1 = "69cb95a7c1fd39e303c172204d78fccd752e5686"
libc = "glibc"
os = "linux"

    [[libxls.download]]
    sha256 = "87c35e99bb5d30c865683bda5d58f4fed5934aafe0767a88c654cbedea697014"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.aarch64-linux-gnu.tar.gz"
[[libxls]]
arch = "aarch64"
git-tree-sha1 = "44e14b0ecb2d1c03fdbb0fda4b40b77368fc32c4"
libc = "musl"
os = "linux"

    [[libxls.download]]
    sha256 = "9ab590ffcaeca9bba6e616a5fb691f31cc4fc1f79306a884c523f9802553b103"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.aarch64-linux-musl.tar.gz"
[[libxls]]
arch = "aarch64"
git-tree-sha1 = "3b03a12beb783c80dbd4a8012a844a6dd1399987"
os = "freebsd"

    [[libxls.download]]
    sha256 = "e3d48a7c0c5be576365743c427f329c7cef7eae2e2d5399df463cfab2923356e"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.aarch64-unknown-freebsd.tar.gz"
[[libxls]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "75d452b7304450005b8915efa32ea56f9d5799f9"
libc = "glibc"
os = "linux"

    [[libxls.download]]
    sha256 = "7afb1c3bd66d96bc6b9f8dfa985413bb2dff9dda6a3bed2529807905402f4589"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.armv6l-linux-gnueabihf.tar.gz"
[[libxls]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0cd1925d70221220716dbeedc5e7859adef6651c"
libc = "musl"
os = "linux"

    [[libxls.download]]
    sha256 = "550e11afafcc6d66706d547e48d5c07ef388d61ca3f4e0155fab407d0ef13bf7"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.armv6l-linux-musleabihf.tar.gz"
[[libxls]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cfb3d87a136b2259a2266a155a432ca4be3086f4"
libc = "glibc"
os = "linux"

    [[libxls.download]]
    sha256 = "57589a692eb05d078ab6c83003cf57afe0bf8ed5c8ecc9dd255d4e90934c0014"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.armv7l-linux-gnueabihf.tar.gz"
[[libxls]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ae5c24f787486e84215e3a5f2179897ac3187b88"
libc = "musl"
os = "linux"

    [[libxls.download]]
    sha256 = "1d17b4a967bf9403e30e1a862f06c2d97c2386a5236ad41f6df4c89d66116fe7"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.armv7l-linux-musleabihf.tar.gz"
[[libxls]]
arch = "i686"
git-tree-sha1 = "0d476eff389d39fe941dcdde1f49e72bfc36d1a2"
libc = "glibc"
os = "linux"

    [[libxls.download]]
    sha256 = "a7c95ec7639efab2fef3a7a81abebddd2b324913aa8702df75c56c7cce89f51c"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.i686-linux-gnu.tar.gz"
[[libxls]]
arch = "i686"
git-tree-sha1 = "10d2520f037a6a9b65705d4e5c8d71d1ca267f86"
libc = "musl"
os = "linux"

    [[libxls.download]]
    sha256 = "0c11b629eea1a8927087bc2264a025a673f97cf9889d25ca6aa1de774bfea439"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.i686-linux-musl.tar.gz"
[[libxls]]
arch = "i686"
git-tree-sha1 = "23af037ad8170a142e59143d897e6a0bf3b0488c"
os = "windows"

    [[libxls.download]]
    sha256 = "b6a96af6c9d1b2140cb6bb4c558a2b7e6813fbb4a6d5579d9a6b09146a7113a6"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.i686-w64-mingw32.tar.gz"
[[libxls]]
arch = "powerpc64le"
git-tree-sha1 = "21a3c448ecdb0c0f5b6f80e479a91e8098265167"
libc = "glibc"
os = "linux"

    [[libxls.download]]
    sha256 = "c34704123eb1e95c71ad84a8454f88d0bc59262d02e95db49ad1bfcedb4f7fa5"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.powerpc64le-linux-gnu.tar.gz"
[[libxls]]
arch = "riscv64"
git-tree-sha1 = "f5673295253a13b78792af14b41ead5b207428e9"
libc = "glibc"
os = "linux"

    [[libxls.download]]
    sha256 = "487a106951fa07d454389415806c7b532b9348c5690404e8d853c51cad1b070b"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.riscv64-linux-gnu.tar.gz"
[[libxls]]
arch = "x86_64"
git-tree-sha1 = "de991af49cb77d9893d41cfe5d9cc248826b95a4"
os = "macos"

    [[libxls.download]]
    sha256 = "0a438147bc2b581433266ea7397dcf6633f5a90874ccc04c5bfe216817a6470b"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.x86_64-apple-darwin.tar.gz"
[[libxls]]
arch = "x86_64"
git-tree-sha1 = "edda3e3f7ce0cf846b1d23bc52e44f435c67add1"
libc = "glibc"
os = "linux"

    [[libxls.download]]
    sha256 = "396b77a1ca4f26fc62c012903058f621739ec8093b4baa9ac5712e2cb08689f1"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.x86_64-linux-gnu.tar.gz"
[[libxls]]
arch = "x86_64"
git-tree-sha1 = "0c99bae66b4ac2341bc85089d9606e0632bfe6fa"
libc = "musl"
os = "linux"

    [[libxls.download]]
    sha256 = "ee9eaf2eedccf3fa1b5e7b300fe9182d44fceaba7271a8a6b1e05debcb631869"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.x86_64-linux-musl.tar.gz"
[[libxls]]
arch = "x86_64"
git-tree-sha1 = "8b567ce5fe94bb08e916c1de0232fae592ae3ad3"
os = "freebsd"

    [[libxls.download]]
    sha256 = "39d89e8e194778decf1612579d4801a186eb0c65f161ab048bca7508413cd14c"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.x86_64-unknown-freebsd.tar.gz"
[[libxls]]
arch = "x86_64"
git-tree-sha1 = "f850a4c910002fe28c5df37bf31ac66bf69c977d"
os = "windows"

    [[libxls.download]]
    sha256 = "9160d0ece7819e35221c88783b3923e65e402df11e85b8735a0cf2fe1b65b91a"
    url = "https://github.com/JuliaBinaryWrappers/libxls_jll.jl/releases/download/libxls-v1.6.3+0/libxls.v1.6.3.x86_64-w64-mingw32.tar.gz"
