# Autogenerated wrapper script for libxls_jll for i686-w64-mingw32
export libxlsreader

JLLWrappers.@generate_wrapper_header("libxls")
JLLWrappers.@declare_library_product(libxlsreader, "libxlsreader-8.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libxlsreader,
        "bin\\libxlsreader-8.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
